services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - APP_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mailping?sslmode=disable
    depends_on:
      - db
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mailping
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
