apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailping-deploy.fullname" . }}-config
  labels:
    {{- include "mailping-deploy.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.appConfig.environment | quote }}
  PORT: {{ .Values.appConfig.port | quote }}