apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailping-deploy.fullname" . }}-secret
  labels:
    {{- include "mailping-deploy.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ include "mailping-deploy.databaseUrl" . | b64enc | quote }}